### ISSUE TITLE
JS Error if PHP script throws exception

### ISSUE THREAD

**Issue by garyns** [iqbalfn/exec-php#1]
If a php script throws an exception, php-exec errors. I had expected the error parameter to contain the error information.

```
/Users/garysmart/Documents/Projects/Gravme/code/trunk/haraka/node_modules/exec-php/index.js:46
        for(var i=0; i<result.length; i++){
                             ^
TypeError: Cannot read property 'length' of undefined
    at /Users/garysmart/Documents/Projects/Gravme/code/trunk/haraka/node_modules/exec-php/index.js:46:30
    at /Users/garysmart/Documents/Projects/Gravme/code/trunk/haraka/node_modules/exec-php/lib/cli.js:49:28
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

My js code looks like this:
```
var execPhp = require('exec-php'); // https://www.npmjs.com/package/exec-php
var script = "test.php";
execPhp(script, '/usr/bin/php', function(error, php, output) {
    
    console.log(error);
    console.log(php);
    console.log(output);
    
});
```

I had a large script that threw an exception, but can replicate it with this simple php script:
```
<?php
  throw new Exception("TEST");
```

**Comment by iqbalfn** [comment]
Thank you for the report. It's already fixed on last commit. v0.0.3
